# Autogenerated with DRAKON Editor 1.31

proc Заголовок { } {
    
}

proc Настройка { } {
    
}

proc Программа { } {
    foreach item $collection {
        #item 26
        write $item
    }
}


